#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

if [[ "$OSTYPE" == darwin* ]]; then
  export PAGER=/usr/local/bin/less
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-i -M -R -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

export PATH="$HOME/.cargo/bin:$PATH"
export PATH=~/util:$PATH
export PATH=/usr/local/opt/llvm/bin/:$PATH

command -v foo >/dev/null 2>&1 && eval "$(rbenv init -)"

export PATH=$PATH:$HOME/go/bin

# get python3 for brew
PYTHONPATH=(/usr/local/Cellar/python/*/Frameworks/Python.framework/Versions/Current/bin)

export PATH=$PATH:$PYTHONPATH[1]

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# load emsdk env if present
emscriptenv() {
  if [ -f ~/emsdk/emsdk_env.sh ]; then
    source ~/emsdk/emsdk_env.sh
      elif [ -f ~/Documents/emsdk/emsdk_env.sh ]; then
# common place for it to exist on macos
      source ~/Documents/emsdk/emsdk_env.sh
      fi
}
