#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

echo executing zshrc

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

stty -ixon
stty -ixoff

export PATH=~/bin:~/util:$PATH
export PATH=~/Documents/personal-utility/scripts:$PATH

. ~/.aliases.sh

export KEYTIMEOUT=1
